modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="struts"
version="${mod_version}"
displayName="Strut Your Stuff"
authors="Cake"
description='''Extracted girder strut library for Forge.'''

[[mixins]]
config="struts.mixins.json"

[[dependencies.struts]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
